apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-booking-system-config
data:
  database_url: mongodb-service
  database_user_db: user_db
  user_service_url: user-service:4000
  payment_service_url: payment-service:4002
