apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: scalable-services-project
type: Opaque
data:
  mongodb-root-username: YWRtaW4=  # base64 encoded "admin"
  mongodb-root-password: cGFzc3dvcmQ=  # base64 encoded "password"