apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: movie-service:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        env:
        - name: MONGODB_ADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              name: movie-booking-system-secret
              key: mongodb-root-username
        - name: MONGODB_ADMIN_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-booking-system-secret
              key: mongodb-root-password
        - name: PORT
          value: "4000"
        - name: MONGODB_URL_PATH
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: database_url
        - name: MONGODB_USER_DB
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: database_user_db
        - name: MONGODB_URL
          value: "mongodb://$(MONGODB_ADMIN_USER_NAME):$(MONGODB_ADMIN_USER_PASSWORD)@$(MONGODB_URL_PATH)/$(MONGODB_USER_DB)?authSource=admin"
        - name: DB_CONNECTION_RETRY_TIMEOUT  
          value: "5000"          
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: movie-booking-system-config
              key: user_service_url